### PR TITLE
Add a common package for pmon

### PR DESCRIPTION
**Pull request by kevinwangsk**
Extract the common part of daemons, and wrap it in a separate package.
Daemons just need to import this package.

Signed-off-by: Kevin Wang <kevinw@mellanox.com>

### CODE REVIEW

**Review by jleveque — CHANGES_REQUESTED** [review]
I think this should be renamed to something along the lines of "sonic_daemon_common", as it supplies common functionality to all deamons.

Also, I think this is a great idea that transcends the pmon Docker container, as we have daemons running in other containers as well as in the base image which contain duplicate code provided here I think this package could be used throughout SONiC, and not just be confined to the pmon container. I think it should be installed in the base image and in docker-base, so that it is available in all Docker containers.

**Review by andriymoroz-mlnx — APPROVED** [review]

**Comment by kevinwangsk** [comment]
> I think this should be renamed to something along the lines of "sonic_daemon_common", as it supplies common functionality to all deamons.
> 
> Also, I think this is a great idea that transcends the pmon Docker container, as we have daemons running in other containers as well as in the base image which contain duplicate code provided here I think this package could be used throughout SONiC, and not just be confined to the pmon container. I think it should be installed in the base image and in docker-base, so that it is available in all Docker containers.

Renamed to "sonic-daemon-common".
Agree that we can make this package to be a part of the base image, not just the pmon container. 
Another thing Joe, I don't touch the LED stuff here as led daemon is not running on our platform.  I can change it as well but may need your help to test it, what do you think?

**Comment by jleveque** [comment]
Yes, please go ahead and modify the LED daemon to use this. I will test it.

Also, I think this package should reside under src/sonic-daemon-common in sonic-buildimage, and the package should be added to the pmon Docker's dependencies in rules/docker-platform-monitor.mk.

**Comment by kevinwangsk** [comment]
> src/sonic-daemon-commo

Have changed for led as well.
For the location of this package, if we move it to src/sonic-daemon-common, should we create a separate repo for it as all the other sonic-* directories are in a separate repo?

**Comment by jleveque** [comment]
I don't think it needs its own repo. For example, sonic-config-engine doesn't have its own repo, it lives in /src but it is part of sonic-buildimage.

**Comment by kevinwangsk** [comment]
> I don't think it needs its own repo. For example, sonic-config-engine doesn't have its own repo, it lives in /src but it is part of sonic-buildimage.

Ok, I'll create the PR to move this package in sonic-buildimage. Once it is merged, there will be another PR to change the daemons in sonic-platform-daemons repo.

**Pull request closed without merging**
